# Generated by Django 2.0.7 on 2019-08-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='title',
        ),
        migrations.AddField(
            model_name='search',
            name='destination',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
